name: try_make
on: [push]
jobs:
  run_make:
    runs-on: ubuntu-latest 
    steps:
      - uses: egor-tensin/setup-gcc@v1  
      - name: try_make
        working-directory: Mexanobar/sci_practice_21-22/build
        run: make