name: try_make
on: [push]
jobs:
  run_make:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2  
      - name: Install GCC
        uses: egor-tensin/setup-gcc@v1
      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.11
      - name: Remove /build directory
        uses: JesseTG/rm@v1.0.0
        with:
          path: ${{ github.workspace }}/build
      - name: Try make
        run: |
          mkdir build
          cd ${{ github.workspace }}/build
          cmake ..
          make
  
