name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v2  
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: move to /build
        run: cd build
      - name: list files in /build
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."